import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  weight: "400",
  subsets: ["latin-ext"],
  display: "swap",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} max-w-[1320px] px-4 mx-auto bg-[#061c26]`}
      >
        {children}
      </body>
    </html>
  );
}

export { metadata };
